<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#143c36"><meta name="description" content="Skybook: cari kursi penerbangan, pesan perjalanan, dan coba pembayaran QR dalam satu tempat."><title><?= esc($title) ?> · Skybook</title><link rel="stylesheet" href="/assets/app.css"><script src="/assets/app.js" defer></script></head>
<body data-page="<?= esc($page) ?>" data-ticket="<?= esc($ticketId ?? '') ?>" data-payment="<?= esc($paymentToken ?? '') ?>">
<header class="site-header"><div class="nav-wrap"><a class="brand" href="/" aria-label="Skybook beranda"><span class="brand-mark">↗</span> skybook<span class="brand-dot">.</span></a><button class="menu-toggle" aria-label="Buka navigasi" aria-expanded="false">☰</button><nav aria-label="Navigasi utama"><a href="/flights" <?= $page === 'flights' ? 'aria-current="page"' : '' ?>>Cari penerbangan</a><a href="/bookings" <?= $page === 'bookings' ? 'aria-current="page"' : '' ?>>Perjalanan saya</a><a href="/docs">API docs <span aria-hidden="true">↗</span></a></nav><div id="auth-nav"><a class="nav-login" href="/login">Masuk</a><a class="button small" href="/register">Buat akun ↗</a></div></div></header>
<main>
<?php if ($page === 'home'): ?>
<section class="hero container"><div class="hero-copy"><div class="eyebrow"><span class="live-dot"></span> LANGKAH KECIL, PERJALANAN BESAR</div><h1>Dunia menanti.<br>Yuk, <span>terbang.</span></h1><p>Dari rencana spontan sampai liburan impian.<br>Temukan kursi Anda, kami bantu sisanya.</p><a class="button" href="/flights">Temukan penerbangan <span>↗</span></a><div class="hero-trust"><span class="trust-icon">✓</span><div><strong>Kursi pilihan. Harga transparan.</strong><small>Pesan dengan tenang, berangkat dengan senang.</small></div></div></div><div class="hero-art" aria-label="Ilustrasi perjalanan ke kepulauan tropis" role="img"><div class="art-orbit"></div><span class="art-tag">YOUR NEXT CHAPTER</span><svg viewBox="0 0 600 600" aria-hidden="true"><defs><linearGradient id="sea" x2="0" y2="1"><stop stop-color="#9fcdc4"/><stop offset="1" stop-color="#507f74"/></linearGradient><linearGradient id="hill" x2="0" y2="1"><stop stop-color="#31594b"/><stop offset="1" stop-color="#183e34"/></linearGradient></defs><circle cx="340" cy="186" r="77" fill="#eddba8"/><path d="M0 380 Q160 350 300 382T600 357V600H0Z" fill="url(#sea)"/><path d="M-20 460 Q130 130 225 323 Q305 30 420 383 Q490 300 620 445V600H-20Z" fill="url(#hill)"/><path d="M-20 493Q130 450 280 484T620 493" fill="none" stroke="#d3d3ab" stroke-width="16"/><path d="M50 570Q210 500 380 527T620 518" fill="none" stroke="#aad0c1" stroke-width="2" opacity=".7"/><path d="M150 140Q280 85 415 170" fill="none" stroke="#fff" stroke-width="2" stroke-dasharray="6 9"/><g transform="translate(416 175) rotate(30)"><path d="M-55 0L-5-8 10-55 20-57 15-8 60-1 65 5 15 9 22 40 12 40-5 10-55 8-65 1Z" fill="#fff8e7"/></g></svg><div class="boarding-float"><span class="float-icon">✈</span><div><small>NEXT DESTINATION</small><strong>Bali, Indonesia</strong></div><span class="float-arrow">↗</span></div><div class="art-caption"><span>08°39′ S &nbsp; 115°13′ E</span><span>MAKE MEMORIES ↗</span></div></div></section>
<section class="container search-section"><form id="home-search" class="search-panel"><div class="search-field"><label for="home-route">Perjalanan</label><select id="home-route" name="route"><option value="">Semua destinasi</option><option value="CGK,DPS">Jakarta → Bali</option><option value="SUB,CGK">Surabaya → Jakarta</option><option value="CGK,YIA">Jakarta → Yogyakarta</option></select></div><div class="search-field"><label for="home-date">Tanggal keberangkatan</label><input id="home-date" name="date" type="date" required></div><div class="search-field"><label for="home-time">Waktu favorit</label><select id="home-time" name="time"><option value="">Kapan saja</option><option>09:00</option><option>13:00</option><option>15:00</option></select></div><button class="button" type="submit">Cari penerbangan ↗</button></form></section>
<section class="container destinations"><div class="section-heading"><div><div class="eyebrow">PILIH SUASANA BARU</div><h2>Ke mana hati ingin pergi?</h2></div><a class="text-link" href="/flights">Lihat penerbangan ↗</a></div><div class="destination-grid"><a href="/flights?origin=CGK&destination=DPS" class="destination bali"><div class="destination-art"><span class="sun"></span><span class="mountain"></span><span class="mountain second"></span><span class="destination-index">01 / ESCAPE</span></div><div class="destination-info"><div><small>PULAU DEWATA</small><h3>Bali</h3></div><span>↗</span></div></a><a href="/flights?origin=SUB&destination=CGK" class="destination jakarta"><div class="destination-art"><span class="sun"></span><span class="building one"></span><span class="building two"></span><span class="building three"></span><span class="destination-index">02 / EXPLORE</span></div><div class="destination-info"><div><small>ENERGI IBU KOTA</small><h3>Jakarta</h3></div><span>↗</span></div></a><a href="/flights?origin=CGK&destination=YIA" class="destination jogja"><div class="destination-art"><span class="sun"></span><span class="temple"></span><span class="destination-index">03 / DISCOVER</span></div><div class="destination-info"><div><small>CERITA & BUDAYA</small><h3>Yogyakarta</h3></div><span>↗</span></div></a></div></section>
<section class="container values"><div><span>01</span><h3>Pilih kursi Anda</h3><p>Lihat kursi yang tersedia dan pilih yang paling nyaman.</p></div><div><span>02</span><h3>Pesan dalam hitungan menit</h3><p>Detail perjalanan dan harga terlihat sebelum Anda memesan.</p></div><div><span>03</span><h3>Satu QR, siap berangkat</h3><p>Coba alur pembayaran dummy dengan kode unik untuk setiap pesanan.</p></div></section>
<?php elseif ($page === 'flights'): ?>
<section class="container page-intro"><div class="eyebrow">LET'S FIND YOUR NEXT JOURNEY</div><h1>Temukan penerbangan<span class="brand-dot">.</span></h1><p>Destinasi pilihan, kursi yang pasti. Semua waktu dalam WIB.</p></section><section class="container flight-layout"><aside class="filter-card"><div class="filter-heading"><h3>Sesuaikan perjalanan</h3><span>⚙</span></div><form id="flight-filters"><label>Tanggal<input name="date" type="date" required></label><label>Maskapai<select name="airline" id="airlines"><option value="">Semua maskapai</option></select></label><label>Jam keberangkatan<select name="time"><option value="">Kapan saja</option><option>09:00</option><option>13:00</option><option>15:00</option></select></label><label>Dari<select name="origin"><option value="">Semua kota</option><option value="CGK">Jakarta (CGK)</option><option value="SUB">Surabaya (SUB)</option></select></label><label>Ke<select name="destination"><option value="">Semua kota</option><option value="DPS">Bali (DPS)</option><option value="CGK">Jakarta (CGK)</option><option value="YIA">Yogyakarta (YIA)</option></select></label><button class="button full">Terapkan filter ↗</button><button class="button ghost full" type="button" id="clear-filters">Reset filter</button></form><div class="filter-note">✧ <span>Tiga jadwal setiap hari.<br>Pilih kursi sebelum kehabisan.</span></div></aside><div class="results"><div class="results-heading"><h3 id="result-count">Mencari kursi tersedia…</h3><span class="badge">EKONOMI</span></div><div id="ticket-list" aria-live="polite"></div><div id="pagination" class="pagination"></div></div></section>
<?php elseif (in_array($page, ['login', 'register', 'forgot', 'reset'], true)): ?>
<section class="container auth-layout"><div class="auth-story"><div class="eyebrow">A LITTLE CLOSER TO YOUR NEXT ADVENTURE</div><h1>Setiap perjalanan<br>punya <em>cerita.</em></h1><p>Mulai cerita Anda bersama Skybook.</p><div class="auth-plane" aria-hidden="true">✈</div><div class="story-bottom"><span>YOUR JOURNEY, SIMPLIFIED.</span><span>↗</span></div></div><div class="auth-card"><a href="/" class="text-link">← Kembali ke beranda</a><h2><?= esc($title) ?></h2><p><?= $page === 'register' ? 'Satu akun untuk semua rencana perjalanan Anda.' : ($page === 'login' ? 'Masuk dan lanjutkan rencana perjalanan Anda.' : 'Kami bantu Anda kembali mengakses akun.') ?></p><form id="auth-form">
<?php if ($page === 'register'): ?><label>Nama lengkap<input name="name" autocomplete="name" maxlength="100" required placeholder="Nama sesuai identitas"></label><?php endif ?>
<?php if ($page !== 'reset'): ?><label>Email<input name="email" type="email" autocomplete="email" maxlength="190" required placeholder="nama@email.com"></label><?php endif ?>
<?php if ($page !== 'forgot'): ?><label><?= $page === 'reset' ? 'Password baru' : 'Password' ?><input name="password" type="password" autocomplete="<?= $page === 'login' ? 'current-password' : 'new-password' ?>" minlength="8" maxlength="72" required placeholder="Minimal 8 karakter"></label><?php endif ?>
<?php if ($page === 'login'): ?><a class="forgot-link" href="/forgot-password">Lupa password?</a><?php endif ?>
<div class="form-message" role="status"></div><button class="button full" type="submit"><?= match($page) {'register' => 'Buat akun', 'forgot' => 'Kirim tautan reset', 'reset' => 'Simpan password', default => 'Masuk'} ?> ↗</button></form><div id="demo-reset"></div><p class="auth-switch"><?= $page === 'login' ? 'Belum punya akun? <a href="/register">Daftar sekarang</a>' : 'Sudah punya akun? <a href="/login">Masuk</a>' ?></p></div></section>
<?php elseif ($page === 'checkout'): ?>
<section class="container page-intro"><a class="text-link" href="/flights">← Kembali ke penerbangan</a><h1>Satu langkah lagi<span class="brand-dot">.</span></h1><p>Periksa perjalanan, isi penumpang, lalu pilih pembayaran.</p></section><section class="container checkout-layout"><div><div class="card" id="ticket-detail">Memuat detail tiket…</div><div class="card" id="passenger-card"><div class="step-label">01 / DATA PENUMPANG</div><h2>Siapa yang berangkat?</h2><form id="booking-form"><label>Nama lengkap penumpang<input name="passenger_name" autocomplete="name" maxlength="100" required placeholder="Sesuai identitas penumpang"></label><div class="form-message" role="status"></div><button class="button full">Pesan kursi ini ↗</button></form></div></div><aside class="card payment-card"><div class="step-label">02 / PEMBAYARAN</div><h2>Siap untuk berangkat.</h2><p>Kursi disimpan selama maksimal 15 menit setelah booking.</p><div id="payment-section"><div class="payment-placeholder">✧<p>Detail pembayaran akan muncul setelah kursi dipesan.</p></div></div></aside></section>
<?php elseif ($page === 'bookings'): ?>
<section class="container page-intro"><div class="eyebrow">YOUR ADVENTURES, ALL IN ONE PLACE</div><h1>Perjalanan saya<span class="brand-dot">.</span></h1><p>Rencana berikutnya dan tiket yang sudah dikonfirmasi.</p></section><section class="container"><div id="booking-list" class="booking-grid" aria-live="polite">Memuat perjalanan…</div><div class="card payment-card" id="resume-payment" hidden></div></section>
<?php elseif ($page === 'account'): ?>
<section class="container page-intro"><div class="eyebrow">MAKE YOURSELF AT HOME</div><h1>Akun saya<span class="brand-dot">.</span></h1><p>Kelola informasi Anda untuk perjalanan berikutnya.</p></section><section class="container account-layout"><div class="card"><h2>Informasi pribadi</h2><form id="account-form"><label>Nama lengkap<input name="name" autocomplete="name" required maxlength="100"></label><label>Email<input name="email" autocomplete="email" type="email" required maxlength="190"></label><hr><h3>Ubah password</h3><p class="muted">Isi kedua kolom hanya jika ingin mengganti password.</p><label>Password saat ini<input name="current_password" type="password" autocomplete="current-password"></label><label>Password baru<input name="password" type="password" autocomplete="new-password" minlength="8" maxlength="72"></label><div class="form-message" role="status"></div><button class="button">Simpan perubahan ↗</button></form></div><aside><div class="card"><span class="large-icon">↗</span><h2>Ke mana selanjutnya?</h2><p>Masih banyak cerita menunggu Anda.</p><a class="button ghost" href="/flights">Cari penerbangan</a><button class="text-link logout" id="logout">Keluar dari akun</button></div><details class="card danger"><summary>Hapus akun</summary><p>Akun akan dihapus permanen dan reservasi yang belum dibayar dibatalkan. Tiket yang sudah dibayar tetap tersimpan sebagai riwayat transaksi.</p><form id="delete-form"><label>Konfirmasi password<input type="password" name="password" required autocomplete="current-password"></label><div class="form-message" role="status"></div><button class="button danger-button">Hapus akun permanen</button></form></details></aside></section>
<?php elseif ($page === 'payment'): ?>
<section class="container confirmation"><div class="card"><div class="confirmation-icon" id="confirmation-icon">◌</div><div class="eyebrow">SKYBOOK · PEMBAYARAN DUMMY</div><h1 id="confirmation-title">Memproses pembayaran…</h1><p id="confirmation-message" role="status">Mohon tunggu sebentar. Kami sedang mengonfirmasi kursi Anda.</p><a class="button" href="/bookings">Lihat perjalanan saya ↗</a><p class="muted">Simulasi portofolio. Tidak ada uang yang ditransfer.</p></div></section>
<?php endif ?>
</main><footer class="container site-footer"><div><a class="brand" href="/">↗ skybook.</a><p>Perjalanan baru. Cerita baru.</p></div><div class="footer-right"><a href="/docs">Dokumentasi API ↗</a><span>© <?= date('Y') ?> Skybook · A portfolio by Prakosa</span><small>Demo pemesanan & pembayaran · Tidak menjual tiket sungguhan.</small></div></footer><div id="toast" role="status" hidden></div>
</body></html>
