// Integration tests use real HTTP, MariaDB, JWT and the QR confirmation endpoint.
const assert = require('node:assert/strict');
const base = process.env.TEST_BASE_URL || 'http://localhost:8000';
const {spawn} = require('node:child_process');
function fixture(action,userId,id,start=0) {
  return new Promise((resolve,reject)=>{const args=[...(process.platform==='win32'?['-c','.runtime/php.ini']:[]),'tests/fixtures.php',action,String(userId),String(id),String(start)];const child=spawn('php',args,{shell:false});let output='';let error='';child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>error+=chunk);child.on('error',reject);child.on('exit',code=>{if(code) reject(new Error('Fixture failed: '+error));else {try {resolve(JSON.parse(output));}catch {reject(new Error('Fixture output: '+output+error));}}});});
}
const suffix = Date.now(); let checks = 0;
async function request(path, method='GET', body, token, expected=200) {
  const response = await fetch(base + path, {method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data = await response.json(); assert.equal(response.status,expected,`${method} ${path}: ${JSON.stringify(data)}`); checks++; return data;
}
(async () => {
  const tomorrow = new Date(Date.now()+86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
  const spec = await request('/openapi.json'); assert.equal(spec.openapi,'3.0.3'); assert.equal(Object.keys(spec.paths).length,14);
  await request('/api/users/me','GET',undefined,undefined,401);
  await request('/api/auth/register','POST',{name:'Test',email:'invalid',password:'tiny'},undefined,422);
  const identity={name:'API Traveler',email:`api-${suffix}@example.com`,password:'TravelPass123!'};
  const a=await request('/api/auth/register','POST',identity,undefined,201);
  const b=await request('/api/auth/register','POST',{...identity,email:`other-${suffix}@example.com`},undefined,201);
  await request('/api/auth/register','POST',identity,undefined,422);
  await request('/api/auth/login','POST',{email:identity.email,password:'wrong-password'},undefined,401);
  const login=await request('/api/auth/login','POST',identity); assert.equal(login.user.email,identity.email); assert(!login.user.password_hash);
  await request('/api/users/me','GET',undefined,a.token.slice(0,-8)+'INVALID!',401);
  const airlines=await request('/api/airlines'); assert.equal(airlines.data.length,3);
  const tickets=await request(`/api/tickets?date=${tomorrow}&per_page=60`); assert(tickets.pagination.total>=4); assert.equal(tickets.data.length,Math.min(60,tickets.pagination.total));
  const page2=await request(`/api/tickets?date=${tomorrow}&per_page=60&page=2`); assert.equal(page2.data.length,Math.max(0,tickets.pagination.total-60));
  const filtered=await request(`/api/tickets?date=${tomorrow}&time=09:00&airline=Garuda%20Indonesia`); assert(filtered.pagination.total>0); assert(filtered.data.every(item=>item.airline==='Garuda Indonesia' && item.departure_at.includes('09:00:00')));
  await request('/api/tickets?per_page=0','GET',undefined,undefined,422);
  await request('/api/tickets?time=25:00','GET',undefined,undefined,422);
  await request('/api/tickets?date=2026-02-30','GET',undefined,undefined,422);
  assert.equal((await request('/api/tickets?page=&per_page=')).pagination.per_page,12);
  const ticket=tickets.data[0]; const detail=await request('/api/tickets/'+ticket.id); assert.equal(detail.payment_methods.length,3); assert.equal(detail.ticket.available,true);
  await request('/api/book','POST',{ticket_id:ticket.id,passenger_name:identity.name},undefined,401);
  const booking=await request('/api/book','POST',{ticket_id:ticket.id,passenger_name:identity.name},a.token,201);
  await request('/api/book','POST',{ticket_id:ticket.id,passenger_name:'Other passenger'},b.token,409);
  assert.equal((await request('/api/tickets/'+ticket.id)).ticket.available,false);
  await request('/api/book/'+booking.booking.id,'GET',undefined,b.token,404);
  await request('/api/pay','POST',{booking_id:booking.booking.id,payment_method:'qris'},b.token,404);
  await request('/api/pay','POST',{booking_id:booking.booking.id,payment_method:'invalid'},a.token,422);
  const payment=await request('/api/pay','POST',{booking_id:booking.booking.id,payment_method:'qris'},a.token);
  const repeated=await request('/api/pay','POST',{booking_id:booking.booking.id,payment_method:'qris'},a.token); assert.equal(payment.payment_url,repeated.payment_url);
  const qr=await fetch(payment.barcode_url,{headers:{Authorization:'Bearer '+a.token}}); assert.equal(qr.status,200);assert((await qr.text()).includes('<svg'));checks++;
  const badQr=await fetch(payment.barcode_url,{headers:{Authorization:'Bearer '+b.token}});assert.equal(badQr.status,404);checks++;
  const code=payment.payment_url.split('/').pop();assert.match(code,/^[a-f0-9]{64}$/);
  await request('/api/payments/'+code+'/confirm','POST',{});
  const paid=await request('/api/book/'+booking.booking.id,'GET',undefined,a.token);assert.equal(paid.booking.status,'paid');assert(!paid.booking.payment_token);
  assert.equal((await request('/api/tickets/'+ticket.id)).ticket.status,'closed');
  await request('/api/payments/'+code+'/confirm','POST',{});
  await request('/api/payments/'+ '0'.repeat(64) + '/confirm','POST',{},undefined,404);
  await request('/api/book','POST',{ticket_id:ticket.id,passenger_name:identity.name},a.token,409);
  const ticket2=tickets.data[1];const booking2=await request('/api/book','POST',{ticket_id:ticket2.id,passenger_name:identity.name},a.token,201);
  const payment2=await request('/api/pay','POST',{booking_id:booking2.booking.id,payment_method:'ewallet'},a.token);assert.notEqual(payment2.payment_url,payment.payment_url);
  const expiring=await request('/api/book','POST',{ticket_id:tickets.data[2].id,passenger_name:identity.name},a.token,201);
  const stalePayment=await request('/api/pay','POST',{booking_id:expiring.booking.id,payment_method:'qris'},a.token);
  await fixture('expire',a.user.id,expiring.booking.id);
  assert.equal((await request('/api/book/'+expiring.booking.id,'GET',undefined,a.token)).booking.status,'expired');
  assert.equal((await request('/api/tickets/'+tickets.data[2].id)).ticket.available,true);
  await request('/api/payments/'+stalePayment.payment_url.split('/').pop()+'/confirm','POST',{},undefined,409);
  await request('/api/book','POST',{ticket_id:tickets.data[2].id,passenger_name:identity.name},a.token,201);
  await request('/api/payments/'+stalePayment.payment_url.split('/').pop()+'/confirm','POST',{},undefined,404);
  const start=Date.now()/1000+1;
  const racers=await Promise.all([fixture('race',a.user.id,tickets.data[3].id,start),fixture('race',a.user.id,tickets.data[3].id,start)]);
  assert.deepEqual(racers.map(item=>item.code).sort(),[201,409]);checks++;
  await request('/api/users/me','PATCH',{name:'Updated Traveler',email:identity.email},a.token);
  const forgot=await request('/api/auth/forgot-password','POST',{email:identity.email});assert(forgot.demo_reset_url);
  const resetToken=new URL(forgot.demo_reset_url).searchParams.get('token');
  await request('/api/auth/reset-password','POST',{token:resetToken,password:'NewTravelPass123!'});
  await request('/api/auth/reset-password','POST',{token:resetToken,password:'AnotherPass123!'},undefined,422);
  await request('/api/users/me','GET',undefined,a.token,401);
  const fresh=await request('/api/auth/login','POST',{email:identity.email,password:'NewTravelPass123!'});
  await request('/api/users/me','PATCH',{name:identity.name,email:identity.email,current_password:'wrong',password:'ChangedPass123!'},fresh.token,403);
  const changed=await request('/api/users/me','PATCH',{name:identity.name,email:identity.email,current_password:'NewTravelPass123!',password:'ChangedPass123!'},fresh.token);
  await request('/api/users/me','DELETE',{password:[]},changed.token,422);
  await request('/api/users/me','GET',undefined,fresh.token,401);
  await request('/api/users/me','DELETE',{password:'ChangedPass123!'},changed.token);
  assert.equal((await request('/api/tickets/'+ticket2.id)).ticket.available,true);
  await request('/api/payments/'+payment2.payment_url.split('/').pop()+'/confirm','POST',{},undefined,404);
  await request('/api/users/me','GET',undefined,changed.token,401);
  await request('/api/auth/logout','POST',{},b.token);
  await request('/api/users/me','GET',undefined,b.token,401);
  const again=await request('/api/auth/login','POST',{email:`other-${suffix}@example.com`,password:identity.password});
  await request('/api/users/me','DELETE',{password:identity.password},again.token);
  console.log(`PASS: ${checks} HTTP integration checks (auth, filters, ownership, booking, payment, token revocation).`);
})().catch(error=>{console.error(error);process.exitCode=1;});
